-- MySQL Script generated by MySQL Workbench
-- Sat Nov 16 11:51:10 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema NotaFiscal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NotaFiscal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NotaFiscal` DEFAULT CHARACTER SET utf8 ;
USE `NotaFiscal` ;

-- -----------------------------------------------------
-- Table `NotaFiscal`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaFiscal`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `CPF` VARCHAR(90) NOT NULL,
  `Nome` VARCHAR(90) NOT NULL,
  `Email` VARCHAR(90) NOT NULL,
  `Celular` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Pontos` DOUBLE NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `NotaFiscal`.`Estabelecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaFiscal`.`Estabelecimento` (
  `idEstabelecimento` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Local` VARCHAR(45) NOT NULL,
  `CNPJ` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstabelecimento`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `NotaFiscal`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaFiscal`.`Compra` (
  `idCompra` INT NOT NULL AUTO_INCREMENT,
  `Valor` DOUBLE NOT NULL,
  `Data` DATE NOT NULL,
  `Compra_User` INT NOT NULL,
  `Compra_Estabelecimento` INT NOT NULL,
  PRIMARY KEY (`idCompra`),
  INDEX `fk_Compra_User_idx` (`Compra_User` ASC) VISIBLE,
  INDEX `fk_Compra_Estabelecimento1_idx` (`Compra_Estabelecimento` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_User`
    FOREIGN KEY (`Compra_User`)
    REFERENCES `NotaFiscal`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_Estabelecimento1`
    FOREIGN KEY (`Compra_Estabelecimento`)
    REFERENCES `NotaFiscal`.`Estabelecimento` (`idEstabelecimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `NotaFiscal`.`ADM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaFiscal`.`ADM` (
  `idADM` INT NOT NULL AUTO_INCREMENT,
  `CPF` VARCHAR(90) NOT NULL,
  `Nome` VARCHAR(90) NOT NULL,
  `Email` VARCHAR(90) NOT NULL,
  `Celular` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idADM`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;

INSERT INTO ADM (CPF, Nome, Email, Celular, Senha) VALUES
('15161444657', 'Felipe Mendes', 'felipe.davila.bh@gmail.com', '31971740540', 'robin'),
('14578455856', 'Maria Eduarda', 'duda@gmail.com', '31975489526', '123');

INSERT INTO Estabelecimento (Nome, Local, CNPJ) VALUES
('CAIXA', 'BH', '12.345.678/0001-90'),
('Loterica Green', 'SP', '98.765.432/0001-01');

INSERT INTO User (Nome, Email, Celular, Senha, CPF, Pontos) VALUES ('Marcio Fantini', 'mf@gmail.com', '31999555724', '123', 'cpf', 0);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
